name: Gradle Package

on:
  push:
    branches:
      - main
      - legacy-stat

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publishShuffler-catalogPublicationToShuffler-catalogRepository
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
